# Generated by Django 5.1.6 on 2025-03-22 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=150)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_description', models.TextField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='gym/event_images')),
            ],
        ),
    ]
