# Generated by Django 5.1.6 on 2025-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('gym_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('gym_name', models.CharField(max_length=100, unique=True)),
                ('gym_city', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=150)),
                ('opening_hours', models.CharField(default='6:00 AM - 10:00 PM', max_length=100)),
                ('gym_image', models.ImageField(blank=True, null=True, upload_to='gym/gym_images')),
            ],
        ),
    ]
