# Generated by Django 5.1.6 on 2025-03-22 21:01

import django.db.models.deletion
import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('specialization', models.CharField(default='General Fitness', max_length=50)),
                ('experience', models.TextField()),
                ('about_trainer', models.TextField(blank=True, null=True)),
                ('trainer_pic', models.ImageField(blank=True, null=True, upload_to='gym/trainers', validators=[gym.models.validate_image_size])),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='gym.gym')),
            ],
        ),
    ]
