# Generated by Django 5.1.6 on 2025-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Brief description of the workout')),
                ('video', models.FileField(blank=True, null=True, upload_to='gym/work_video')),
            ],
        ),
    ]
