# Generated by Django 5.1.6 on 2025-03-22 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('about_user', models.TextField(default='')),
                ('user_cv', models.FileField(blank=True, null=True, upload_to='gym/user_cv')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
