# Generated by Django 5.1.6 on 2025-03-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_applicantdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('calories_per_day', models.PositiveIntegerField(help_text='Total daily calorie intake')),
                ('meals', models.TextField(help_text='Enter meal details (e.g., breakfast, lunch, dinner, snacks, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
        ),
    ]
