# Generated by Django 5.1.6 on 2025-03-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_querydoubt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ResourceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('workout_type', models.CharField(choices=[('Strength', 'Strength Training'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility'), ('Endurance', 'Endurance'), ('Balance', 'Balance')], default='Strength', max_length=50)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='gym/workouts/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/workouts/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_resources', to='gym.gym')),
            ],
        ),
    ]
