# Generated by Django 5.1.6 on 2025-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_rename_date_member_date_joined_member_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
