# Generated by Django 5.1.6 on 2025-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_gym_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='owner_name',
            field=models.CharField(default='Gym', max_length=100),
            preserve_default=False,
        ),
    ]
