# Generated by Django 5.1.6 on 2025-03-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_gym_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querydoubt',
            name='member_id',
        ),
        migrations.AddField(
            model_name='querydoubt',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gym.member'),
        ),
    ]
