# Generated by Django 5.1.6 on 2025-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_querydoubt_member_id_querydoubt_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcework',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
