# Generated by Django 5.1.6 on 2025-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_alter_resourcework_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment',
            field=models.BooleanField(default=True),
        ),
    ]
