# Generated by Django 5.1.6 on 2025-04-01 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_alter_member_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.CharField(default='', max_length=50)),
                ('news_title', models.CharField(max_length=100)),
                ('news_description', models.TextField()),
                ('news_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='gym_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
