# Generated by Django 5.1.6 on 2025-04-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Abs', 'Abs'), ('Full Body', 'Full Body'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility')], max_length=60)),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_image', models.ImageField(upload_to='gym/gym_facilities')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='gym.gym')),
            ],
        ),
    ]
