# Generated by Django 5.1.6 on 2025-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_gymfacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetail',
            name='gym_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
